### PR TITLE
actual init with empty boilerblate

### PR DESCRIPTION
**Pull request by SirCotare**

### CODE REVIEW

**Review by Piiit — APPROVED** [review]
LGTM, would add the IntelliJ config here... wdyt?

**Comment by Piiit** [comment]
Would check that the deploy goes through...

**Comment by SirCotare** [comment]
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< it.aboutbits:spring-boot-toolbox >------------------
[INFO] Building spring-boot-toolbox BUILD-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- checkstyle:3.2.1:check (validate) @ spring-boot-toolbox ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ spring-boot-toolbox ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/andreashufler/code/lib/spring-boot-toolbox/src/main/resources
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ spring-boot-toolbox ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ spring-boot-toolbox ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /Users/andreashufler/code/lib/spring-boot-toolbox/src/test/resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ spring-boot-toolbox ---
[INFO] No sources to compile
[INFO] 
[INFO] --- surefire:3.1.2:test (default-test) @ spring-boot-toolbox ---
[INFO] No tests to run.
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ spring-boot-toolbox ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: /Users/andreashufler/code/lib/spring-boot-toolbox/target/spring-boot-toolbox-BUILD-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.854 s
[INFO] Finished at: 2024-08-09T15:24:17+02:00
[INFO] ------------------------------------------------------------------------
```

**Review by Piiit — APPROVED** [review]
LGTM

**Pull request merged**
